---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioner
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: provisioner
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["create", "update", "patch", "get", "list", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: provisioner
subjects:
- kind: ServiceAccount
  name: provisioner
  namespace: kube-system
